services:
  postgres:
    image: postgres:14
    container_name: server_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco
      POSTGRES_DB: universidade
    ports:
      - "5432:5432"


  app:  
    build: ./projeto/.
    container_name: app_asa            
    ports:
      - "8000:8000"
    depends_on:
      - postgres

