version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco123
      POSTGRES_DB: universidade
    volumes:
      - /home/euler/dados_postgresql:/var/lib/postgresql/data
    networks:
      app-network:
        ipv4_address: 172.20.0.2

  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      app-network:
        ipv4_address: 172.20.0.3
    environment:
      DATABASE_URL: postgresql://postgres:banco123@172.20.0.2/universidade

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16